projects/1.1.BasicDjango/d05/d05/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ex00/', include('ex00.urls')),
    path('ex01/', include('ex01.urls')),
    path('admin/', admin.site.urls),
]

projects/1.1.BasicDjango/d05/ex00/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

projects/1.1.BasicDjango/d05/ex01/urls.py
from django.urls import path
from . import views

app_name = "ex01"
urlpatterns = [
    path("django", views.django_view, name="django"),
    path("display", views.display_view, name="display"),
    path("templates", views.templates_view, name="templates"),
]

projects/1.1.BasicDjango/d05/ex01/models.py
from django.db import models

# Create your models here.

projects/1.1.BasicDjango/d05/ex00/views.py
from django.shortcuts import render


def index(request):
    return render(request, "ex00/index.html")

projects/1.1.BasicDjango/d05/ex01/views.py
from django.shortcuts import render


def django_view(request):
    return render(request, "ex01/django.html")


def display_view(request):
    return render(request, "ex01/display.html")


def templates_view(request):
    return render(request, "ex01/templates.html")

projects/1.1.BasicDjango/d05/ex00/templates/ex00/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Ex00: Markdown Cheatsheet</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 40px;
            }
            code {
                background-color: #f9f9f9;
                border: 1px solid #d1d1d1;
                padding: 2px 6px;
            }
        </style>
    </head>
    <body>
        <h1>Ex00: Markdown Cheatsheet</h1>
        <p>This cheatsheet provides a basic overview of Markdown syntax:</p>

        <h2>Headers</h2>
        <code># This is an &lt;h1&gt; tag</code><br />
        <code>## This is an &lt;h2&gt; tag</code><br />
        <code>###### This is an &lt;h6&gt; tag</code>

        <h2>Emphasis</h2>
        <code>*This text will be italic*</code><br />
        <code>**This text will be bold**</code><br />
        <code>_You **can** combine them_</code>

        <h2>Lists</h2>
        <h3>Unordered</h3>
        <code>* Item 1</code><br />
        <code>* Item 2</code><br />
        <code> * Item 2a</code><br />
        <code> * Item 2b</code>

        <h3>Ordered</h3>
        <code>1. Item 1</code><br />
        <code>2. Item 2</code><br />
        <code>3. Item 3</code><br />
        <code> 1. Item 3a</code><br />
        <code> 2. Item 3b</code>

        <h2>Links</h2>
        <code>[Visit GitHub!](http://github.com)</code>

        <h2>Images</h2>
        <code>![GitHub Logo](/images/logo.png)</code><br />
        <code>Format: ![Alt Text](url)</code>

        <h2>Blockquotes</h2>
        <code>&gt; This is a blockquote.</code>

        <h2>Inline code</h2>
        <code>`This is inline code`</code>

        <h2>Code Blocks</h2>
        <code
            >```<br />
            This is a code block<br />
            ```</code
        >

        <h2>Tables</h2>
        <code>| Heading | Heading |</code><br />
        <code>| --- | --- |</code><br />
        <code>| Data | Data |</code><br />
        <code>| Data | Data |</code>

        <p>
            For more details, visit the
            <a href="https://www.markdownguide.org/cheat-sheet/"
                >Markdown Guide</a
            >.
        </p>
    </body>
</html>

projects/1.1.BasicDjango/d05/ex01/templates/ex01/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <h1>{% block title %} {% endblock %}</h1>
        {% block style %} {% endblock %}
    </head>
    <body>
        {% include './nav.html' %}
        {% block content %} {% endblock %}
    </body>
</html>

projects/1.1.BasicDjango/d05/ex01/templates/ex01/display.html
{% extends 'ex01/base.html' %}
{% load static %}

{% block title %}Ex01: Display process of a static page.{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'static/style1.css' %}">
{% endblock %}

{% block content %}
<h2>정적 페이지 처리 과정</h2>
<p>Django에서 정적 웹페이지가 사용자에게 어떻게 전달되는지에 대한 과정은 다음과 같습니다:</p>

<ol>
    <li><strong>요청 수신:</strong> 사용자가 웹 브라우저를 통해 특정 URL로 요청을 보냅니다. 예를 들어, 사용자가 ‘/ex01/display’ 페이지를 요청한다고 가정해 봅시다.</li>
    <li><strong>URL 라우터:</strong> Django의 URL 라우터는 요청받은 URL을 분석하고, 이를 urlpatterns에서 정의된 패턴과 비교하여 해당 요청을 처리할 뷰 함수를 결정합니다.</li>
    <li><strong>뷰 함수:</strong> URL 라우터에 의해 선택된 뷰 함수가 호출됩니다. 이 함수는 요청을 처리하고, 응답을 생성하기 위해 필요한 모든 데이터를 처리합니다.</li>
    <li><strong>템플릿 렌더링:</strong> 뷰는 응답을 구성하기 위해 템플릿을 사용합니다. 뷰는 템플릿 엔진에게 HTML 파일 내에서 사용할 데이터를 전달합니다.</li>
    <li><strong>HTML 파일:</strong> 템플릿 엔진은 전달받은 데이터와 HTML 템플릿을 결합하여 최종적인 HTML 응답을 생성합니다.</li>
    <li><strong>응답 전송:</strong> 생성된 HTML 응답이 사용자의 웹 브라우저로 전송되어 페이지가 표시됩니다.</li>
</ol>

<p>이 과정을 통해 Django는 정적 페이지 요청을 효율적으로 처리하며, 개발자는 URL 라우팅, 뷰 함수, 그리고 템플릿을 통해 웹 페이지를 사용자에게 제공할 수 있습니다.</p>
{% endblock %}

projects/1.1.BasicDjango/d05/ex01/templates/ex01/django.html
{% extends 'ex01/base.html' %}
{% load static %}

{% block title %}Ex01: Django, framework web{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'static/style1.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>장고(Django)란?</h1>
    <p>장고(Django)는 파이썬으로 작성된 고급 웹 프레임워크입니다. 개발자가 빠르고, 깔끔하며, 실용적인 웹 사이트를 구축할 수 있도록 설계되었습니다. 'Django'라는 이름은 재즈 기타리스트 'Django Reinhardt'에서 가져온 것입니다.</p>
    
    <h2>장고의 역사</h2>
    <p>장고는 2005년에 공개되었으며, 원래는 로렌스 저널-월드 신문사의 웹 개발을 위해 생성되었습니다. 장고는 '재사용 가능한 앱'의 개념을 도입하여 웹 개발의 속도와 효율성을 대폭 향상시켰습니다.</p>
    
    <h2>장고의 주요 특징</h2>
    <ul>
        <li>강력한 ORM(Object-Relational Mapping): 데이터베이스 작업을 쉽게 할 수 있도록 돕습니다.</li>
        <li>자동화된 관리 인터페이스: 관리자 페이지를 손쉽게 생성할 수 있습니다.</li>
        <li>보안 기능: XSS, CSRF 및 SQL 인젝션과 같은 보안 위협으로부터 보호합니다.</li>
        <li>다양한 미들웨어 지원: 요청과 응답 사이의 다양한 작업을 처리할 수 있습니다.</li>
    </ul>
    
    <h2>장고 사용의 이점</h2>
    <p>장고는 '배터리 포함(batteries-included)' 접근 방식을 취하며, 많은 일반적인 웹 개발 과제를 위한 해결책과 도구를 제공합니다. 이를 통해 개발자는 웹 애플리케이션의 기본 구조에 덜 신경 쓰고, 애플리케이션의 특정 기능 개발에 더 집중할 수 있습니다.</p>
</div>

{% endblock %}

projects/1.1.BasicDjango/d05/ex01/templates/ex01/nav.html
<nav>
    <ul>
        <li><a href="{% url 'ex01:django' %}">Django</a></li>
        <li><a href="{% url 'ex01:display' %}">Display</a></li>
        <li><a href="{% url 'ex01:templates' %}">Templates</a></li>
    </ul>
</nav>

projects/1.1.BasicDjango/d05/ex01/templates/ex01/templates.html
{% extends 'ex01/base.html' %}
{% load static %}

{% block title %}Ex01: Template engine.{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'static/style2.css' %}">
{% endblock %}

{% block content %}

<h2>Django 템플릿 엔진</h2>
<p>Django의 템플릿 엔진은 HTML과 Django 템플릿 언어(DTL)를 결합하여 동적 웹 페이지를 생성합니다.</p>

<h3>템플릿의 기본 구조</h3>
<p>템플릿은 HTML 코드에 Django 템플릿 태그와 변수를 포함할 수 있습니다. 태그는 {{ '{%' }} 와 {{ '%}' }}  사이에, 변수는  {{ '{{' }}  와 {{ ''}}' }} 사이에 위치합니다.</p>

<h3>변수 사용</h3>
<p>템플릿에서 변수를 사용하면 뷰에서 전달한 데이터를 HTML 페이지에 삽입할 수 있습니다. 예:  <code>{{ variable_name }}</code></p>

<h3>태그와 필터</h3>
<p>태그는 템플릿 내에서 로직을 실행합니다. 예:  {{ '{%' }} for item in list %} ... {{ '{%' }} endfor  {{ '%}' }}  </code>. 필터는 변수의 출력을 수정합니다. 예: {{ '{{' }} name|lower {{ ''}}' }}</p>

<h3>템플릿 상속</h3>
<p>템플릿 상속을 사용하면 공통 요소를 재사용할 수 있어 코드 중복을 줄일 수 있습니다.  {{ '{%' }} extends 'base.html'  {{ '%}' }}  </code>태그를 사용하여 기본 템플릿을 상속받을 수 있습니다.</p>

<h3>템플릿에서 사용하는 Django 템플릿 언어의 기능</h3>
<ul>
    <li>블록:  {{ '{%' }} block block_name  {{ '%}' }} ... {{ '{%' }} endblock {{ '%}' }} </code>을 사용하여 템플릿에서 오버라이드 가능한 섹션을 정의할 수 있습니다.</li>
    <li>루프:  {{ '{%' }} for item in list  {{ '%}' }} ... {{ '{%' }} endfor {{ '%}' }} </code>을 사용하여 리스트의 항목을 반복하여 표시할 수 있습니다.</li>
    <li>조건문:  {{ '{%' }} if condition  {{ '%}' }} ... {{ '{%' }} endif {{ '%}' }} </code>을 사용하여 조건에 따라 다른 HTML 코드를 표시할 수 있습니다.</li>
    <li>템플릿 필터: {{ '{{' }} variable|filter {{ ''}}' }}를 사용하여 출력을 포맷할 수 있습니다. 예를 들어, 대문자로 변환하거나 날짜 형식을 변경할 수 있습니다.</li>
</ul>

<p>이러한 기능을 사용하여, Django에서는 동적 콘텐츠를 포함하는 유연하고 강력한 웹 페이지를 쉽게 생성할 수 있습니다.</p>

{% endblock %}